version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: unibite_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: unibite
      POSTGRES_PASSWORD: unibite_password
      POSTGRES_DB: unibite_db
    ports:
      - "5432:5432"
    volumes:
      - unibite_pgdata:/var/lib/postgresql/data

volumes:
  unibite_pgdata:
